from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "lab_submission.docx"


def add_code_block(doc, text):
    for line in text.splitlines():
        p = doc.add_paragraph()
        run = p.add_run(line)
        run.font.name = "Courier New"


def main():
    explanation = (ROOT / "lab_dsai_rag_explanation.md").read_text(encoding="utf-8").strip()
    output_text = (ROOT / "lab_dsai_rag_output.md").read_text(encoding="utf-8").strip()
    script_text = (ROOT / "lab_dsai_rag.py").read_text(encoding="utf-8").strip()
    data_text = (ROOT / "data" / "dsai_project_notes.csv").read_text(encoding="utf-8").strip()

    doc = Document()
    doc.add_heading("07 RAG Lab Submission", level=0)

    doc.add_paragraph(
        "This document combines the required materials for the lab: the complete RAG script, "
        "a brief explanation, and the recorded run output."
    )

    doc.add_heading("Brief Explanation", level=1)
    for paragraph in explanation.splitlines():
        if paragraph.strip():
            doc.add_paragraph(paragraph.strip())

    doc.add_heading("Data Source", level=1)
    doc.add_paragraph(
        "Custom CSV file used for retrieval: 07_rag/data/dsai_project_notes.csv"
    )
    add_code_block(doc, data_text)

    doc.add_heading("Run Output", level=1)
    doc.add_paragraph(
        "The following output was generated by running the custom lab script against the local Ollama model."
    )
    add_code_block(doc, output_text)

    doc.add_heading("Complete Script", level=1)
    doc.add_paragraph("File: 07_rag/lab_dsai_rag.py")
    add_code_block(doc, script_text)

    doc.save(OUTPUT)
    print(f"Saved {OUTPUT}")


if __name__ == "__main__":
    main()
